title: ECG - Adaptive Noise Cancellation
description: A website following my research and testing of an alternative way for filtering in heart monitors.
theme: just-the-docs

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

url: https://graceboerner5-jpg.github.io/heart-monitor-redesign

aux_links:
  "GitHub Repository": https://github.com/graceboerner5-jpg/heart-monitor-redesign
footer_content: "Grace Boerner | Biomedical Engineering Student at Georgia Tech" 
